/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbilityScoreBlock: typeof import('./src/components/AbilityScoreBlock.vue')['default']
    ActionStep: typeof import('./src/components/scene/steps/ActionStep.vue')['default']
    ActionStepGroup: typeof import('./src/components/formElements/ActionStepGroup.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CharacterSelectCard: typeof import('./src/components/characterSelect/CharacterSelectCard.vue')['default']
    Column: typeof import('primevue/column')['default']
    DailyScenarioList: typeof import('./src/components/scene/DailyScenarioList.vue')['default']
    DailyScene: typeof import('./src/components/scene/DailyScene.vue')['default']
    DailySceneSummary: typeof import('./src/components/scene/DailySceneSummary.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCard: typeof import('./src/components/layout/ImageCard.vue')['default']
    InventoryList: typeof import('./src/components/InventoryList.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OptionStep: typeof import('./src/components/scene/steps/OptionStep.vue')['default']
    OptionStepList: typeof import('./src/components/scene/steps/OptionStepList.vue')['default']
    PlayerCharacterSelectCard: typeof import('./src/components/playerCharacter/PlayerCharacterSelectCard.vue')['default']
    PlayerCharacterSideBar: typeof import('./src/components/playerCharacter/PlayerCharacterSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioOptionRepeater: typeof import('./src/components/formElements/ScenarioOptionRepeater.vue')['default']
    ScenarioStepRepeater: typeof import('./src/components/formElements/ScenarioStepRepeater.vue')['default']
    ScenarioSteps: typeof import('./src/components/scene/steps/ScenarioSteps.vue')['default']
  }
}
