/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbilityScoreBlock: typeof import('./src/components/AbilityScoreBlock.vue')['default']
    BaseCard: typeof import('./src/components/layout/BaseCard.vue')['default']
    Card: typeof import('./src/components/layout/Card.vue')['default']
    CharacterSelectCard: typeof import('./src/components/characterSelect/CharacterSelectCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCard: typeof import('./src/components/layout/ImageCard.vue')['default']
    Inventory: typeof import('./src/components/Inventory.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlayerCharacterSelectCard: typeof import('./src/components/playerCharacterSelect/PlayerCharacterSelectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
