/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbilityScoreBlock: typeof import('./src/components/AbilityScoreBlock.vue')['default']
    ActionStep: typeof import('./src/components/scene/ActionStep.vue')['default']
    ActionStepGroup: typeof import('./src/components/formElements/ActionStepGroup.vue')['default']
    Button: typeof import('primevue/button')['default']
    CharacterSelectCard: typeof import('./src/components/characterSelect/CharacterSelectCard.vue')['default']
    Column: typeof import('primevue/column')['default']
    DailyScene: typeof import('./src/components/scene/DailyScene.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FormRepeater: typeof import('./src/components/formElements/FormRepeater.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCard: typeof import('./src/components/layout/ImageCard.vue')['default']
    Inventory: typeof import('./src/components/Inventory.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NextStepList: typeof import('./src/components/formElements/NextStepList.vue')['default']
    OptionStep: typeof import('./src/components/scene/OptionStep.vue')['default']
    OptionStepList: typeof import('./src/components/scene/OptionStepList.vue')['default']
    PlayerCharacterSelectCard: typeof import('./src/components/playerCharacter/PlayerCharacterSelectCard.vue')['default']
    PlayerCharacterSideBar: typeof import('./src/components/playerCharacter/PlayerCharacterSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenarioList: typeof import('./src/components/admin/scenarios/ScenarioList.vue')['default']
    ScenarioOption: typeof import('./src/components/scene/ScenarioOption.vue')['default']
    ScenarioOptionRepeater: typeof import('./src/components/formElements/ScenarioOptionRepeater.vue')['default']
    ScenarioOptions: typeof import('./src/components/formElements/ScenarioOptions.vue')['default']
    ScenarioStep: typeof import('./src/components/scene/ScenarioStep.vue')['default']
    ScenarioStepRepeater: typeof import('./src/components/formElements/ScenarioStepRepeater.vue')['default']
    ScenarioSteps: typeof import('./src/components/scene/ScenarioSteps.vue')['default']
  }
}
